version: '3.7'
services:
  react:    
    container_name: react
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - 'APP_ENV=dev'
    stdin_open: true 
    tty: true   
    volumes:
      - '.:/app'
      - '/app/node_modules'      
    ports:
      - '3000:3000'